Implement get and touch functionality
sky-uk/ReactiveCouchbase-core pull request #3
Opened 2017-09-12 15:54 UTC by MarkTickner

2017-09-12 16:19 UTC, paulaylingdev approved these changes

2017-09-13 09:57 UTC, serragnoli requested changes

2017-09-13 09:57 UTC, serragnoli commented on driver/src/main/scala/org/reactivecouchbase/client/Read.scala
> +    * Fetch a optional document and set its expiry
"Fetch an optional..." 😃

2017-09-13 09:57 UTC, serragnoli commented on driver/src/main/scala/org/reactivecouchbase/client/Read.scala
> +      case Some(JsError(errors)) if bucket.jsonStrictValidation => throw new JsonValidationException("Invalid JSON content", JsError.toFlatJson(errors))
It seems "toFlatJson" has been deprecated and its replacement seems straightforward to add.

2018-04-10 14:20 UTC, closed without merging